pipeline{
    agent any
    tools{
        nodejs 'NODEJS23'
    }
    environment
    {
        SONAR_SCANNER_HOME= tool 'sonarqube-7'
    }
    stages{
    
        stage('Install dependencies')
        {
            steps{
            sh '''
                cd backend/
                npm install 
                '''
            }
        }
        stage('npm test')
        {
            steps{
            sh '''
              cd backend
              npm test
              '''
            }
        }
        stage('npm coverage')
        {
            steps{
            sh '''
              cd backend
              npm run coverage
              '''
            }
        }
        stage('SAST-sonarqube')
        {
            steps{
            sh '''
                $SONAR_SCANNER_HOME/bin/sonar-scanner \
                -Dsonar.projectKey=goalsapp \
                -Dsonar.host.url=http://3.108.61.101:9000 \
                -Dsonar.login=sqp_7d30bbc0ee8b709d1c919303f17bfb82a6df6131
        
            '''
            }
        }
    } 
}