pipeline{
    agent any
    tools{
        nodejs 'NODEJS23'
        
    }
    stages{
        stage('Install Dependencies')
        {
            options{timestamps()}
            steps{
            sh '''
               cd backend 
               npm install --no-audit
               '''
            }
        }

        stage('Dendency check-OWASP')
        {
            steps{
            
               dependencyCheck additionalArguments: '--scan backend/ --out backend/OWASP-report  --disableYarnAudit --prettyPrint --format ALL', 
               odcInstallation: 'DC-12'
               
            }
            
        }
    }
}